"use client";

import { Button } from "@heroui/react";
import { formatDistanceToNow } from "date-fns";
import { useInstructions } from "@/hooks/use-instructions";
import { MdEditor } from "@/components/shared/md-editor";
import { VersionHistory } from "@/components/shared/version-history";
import { ActivityLog } from "@/components/telegram/activity-log";
import { useTelegramFormatter } from "@/hooks/use-telegram-formatter";
import { toast } from "sonner";

export function FormatLogicView() {
  const { instructions, activeInstruction, createVersion, setActive } =
    useInstructions("telegram", "telegram_format");
  const { history } = useTelegramFormatter();

  async function handleSave(content: string) {
    try {
      await createVersion(content, "Updated formatting rules");
      toast.success("New version created");
    } catch {
      toast.error("Failed to save");
    }
  }

  async function handleActivate(id: string) {
    try {
      await setActive(id);
      toast.success("Version activated");
    } catch {
      toast.error("Failed to activate");
    }
  }

  return (
    <div className="flex flex-col">
      <section className="px-8 py-8 grid grid-cols-12 gap-8">
        {/* Left: Editor */}
        <div className="col-span-8 flex flex-col gap-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className=" text-lg font-bold text-[var(--sw-text)]">
                Formatting Engine
              </h3>
              <p className="text-xs text-[var(--sw-text-secondary)]">
                Configure the Markdown logic that drives Telegram post
                generation
              </p>
            </div>
            <Button
              onPress={() =>
                activeInstruction &&
                handleSave(activeInstruction.content)
              }
              variant="primary"
              size="sm"
              className="flex items-center gap-2 px-4 py-2 rounded-lg font-bold text-xs shadow-sm"
            >
              <span className="material-symbols-outlined text-sm">save</span>
              <span>Save Changes</span>
            </Button>
          </div>

          {activeInstruction && (
            <MdEditor
              filename={`${activeInstruction.slug ?? "telegram_format"}_v${activeInstruction.version}.md`}
              content={activeInstruction.content}
              version={activeInstruction.version}
              isLive
              lastSynced={activeInstruction.updated_at ? formatDistanceToNow(new Date(activeInstruction.updated_at), { addSuffix: true }) : "unknown"}
              onSave={handleSave}
            />
          )}
        </div>

        {/* Right: History + Info */}
        <div className="col-span-4 flex flex-col gap-8">
          <VersionHistory
            instructions={instructions}
            onActivate={handleActivate}
          />

          <div className="p-6 bg-[var(--sw-primary)]/5 rounded-xl border border-[var(--sw-primary)]/10">
            <div className="flex items-center gap-3 mb-4">
              <span className="material-symbols-outlined text-[var(--sw-primary)]">
                info
              </span>
              <h4 className="text-sm font-bold text-[var(--sw-primary)]">Admin Note</h4>
            </div>
            <p className="text-[11px] leading-relaxed text-[var(--sw-text-secondary)]">
              Rules defined here are used as the{" "}
              <strong>System Prompt</strong> for the AI formatter. Any changes
              will immediately affect all posts generated by the team. Please
              test changes in the Formatter tab before saving major updates.
            </p>
          </div>
        </div>

        {/* Activity Log */}
        <div className="col-span-12 mt-4">
          <ActivityLog history={history} />
        </div>
      </section>
    </div>
  );
}
